[tool.poetry]
name = "frheed"
version = "0.0.3"
description = "A GUI for real-time RHEED analysis."
authors = ["Elliot Young <elliot.young1996@gmail.com>"]
readme = "README.md"
packages = [{include = "pyle"}]

[tool.poetry.dependencies]
python = "^3.10.4, <3.11" # PySpin only supports up to 3.10
PyQt5 = "^5.14"
numpy = "^1.23"
opencv-python = "^4.7"
scipy = "^1.9"
pyqtgraph = "^0.13"
cmapy = "0.6.6"
appdirs = "1.4.4"

[tool.black]
line-length = 100
target_version = ["py310"]
skip-string-normalization = true
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
line_length = 100
